# Generated by Django 4.0.1 on 2022-01-15 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='test',
        ),
    ]
