# Generated by Django 4.0.1 on 2022-01-16 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_article_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlesection',
            options={'verbose_name_plural': 'sections'},
        ),
    ]
