# Generated by Django 4.0.1 on 2022-01-16 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_articlesection_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.articlesection'),
        ),
    ]
