# Generated by Django 4.0.1 on 2022-01-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_article_article_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='readingTime',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
