# Generated by Django 4.0.1 on 2022-01-16 12:43

import apps.main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_article_image_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.main.models.article_image_path),
        ),
    ]
