# Generated by Django 4.0.1 on 2022-01-16 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_article_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_section',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='articlesection',
            old_name='article_category',
            new_name='category',
        ),
    ]
