# Generated by Django 4.0.1 on 2022-01-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_article_section_article_section_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='readingTime',
            new_name='readtime',
        ),
        migrations.AddField(
            model_name='article',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='article',
            name='view_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='articlesection',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
