# Generated by Django 4.0.1 on 2022-01-16 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_article_date_alter_article_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 16, 15, 43, 5, 183087)),
        ),
    ]
