# Generated by Django 4.0.1 on 2022-01-16 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='str_date',
            field=models.CharField(blank=True, editable=False, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 16, 15, 46, 54, 474105)),
        ),
    ]
