# Generated by Django 4.0.1 on 2022-01-17 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_article_date_alter_articlesection_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesection',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 14, 6, 19, 237865)),
        ),
    ]
