# Generated by Django 4.0.1 on 2022-01-17 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_articlesection_order_category_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 14, 8, 37, 888506)),
        ),
    ]
