# Generated by Django 4.0.1 on 2022-01-25 16:02

import apps.main.models
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_category_options_alter_article_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 16, 2, 45, 535895)),
        ),
        migrations.CreateModel(
            name='PromptAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_by', models.CharField(max_length=160)),
                ('is_youtube', models.BooleanField(default=False)),
                ('youtube_link', models.CharField(blank=True, max_length=160, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.main.models.prompt_image_path)),
                ('video', models.FileField(blank=True, null=True, upload_to=apps.main.models.prompt_video_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.prompt')),
            ],
        ),
    ]
