# Generated by Django 4.0.1 on 2022-01-25 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_prompt_alter_article_date_promptanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 16, 25, 27, 944966)),
        ),
    ]
