# Generated by Django 4.0.1 on 2022-01-25 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_promptanswer_video_alter_article_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promptanswer',
            old_name='video',
            new_name='video_file',
        ),
        migrations.RemoveField(
            model_name='promptanswer',
            name='is_youtube',
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 17, 14, 14, 687616)),
        ),
    ]
