# Generated by Django 4.0.1 on 2022-01-25 17:24

import apps.main.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptanswer',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=apps.main.models.prompt_image_path),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 17, 24, 36, 485933)),
        ),
    ]
