# Generated by Django 4.0.1 on 2022-01-25 22:07

import apps.main.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_remove_promptanswer_is_youtube_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptanswer',
            name='is_youtube',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='promptanswer',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=apps.main.models.prompt_image_path),
        ),
        migrations.AddField(
            model_name='promptanswer',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.main.models.prompt_video_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 22, 7, 53, 965553)),
        ),
    ]
