# Generated by Django 4.0.1 on 2022-01-27 12:34

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_alter_article_date_alter_promptanswer_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='category'),
            preserve_default=False,
        ),
    ]
