# Generated by Django 4.0.1 on 2022-01-27 12:42

import apps.main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveSmallIntegerField(default=apps.main.models.get_order_default),
        ),
    ]
