# Generated by Django 4.0.1 on 2022-01-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_populate_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesection',
            name='slug',
            field=models.SlugField(default=1, editable=False, max_length=160),
            preserve_default=False,
        ),
    ]
