# Generated by Django 4.0.1 on 2022-01-27 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_alter_article_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promptanswer',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='promptanswer',
            name='video_file',
        ),
    ]
