# Generated by Django 4.0.1 on 2022-01-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_remove_promptanswer_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='1', editable=False, max_length=160),
        ),
    ]
