# Generated by Django 4.0.1 on 2022-01-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_populate_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(editable=False, max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='articlesection',
            name='slug',
            field=models.SlugField(editable=False, max_length=160, unique=True),
        ),
    ]
