# Generated by Django 4.0.1 on 2022-01-28 16:02

import apps.main.models
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_alter_article_slug_alter_articlesection_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(editable=False, max_length=160, unique=True)),
                ('description', ckeditor.fields.RichTextField(max_length=300)),
                ('favorite_link', models.CharField(max_length=160)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.main.models.podcast_image_path)),
                ('provider', models.CharField(choices=[('APPLE', 'Apple Podcasts'), ('SPOTIFY', 'Spotify'), ('IHEART', 'iHeart'), ('STITCHER', 'Stitcher')], default='APPLE', max_length=50)),
            ],
        ),
    ]
